#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

use Mrazinshaikh\LaravelMigration\CommandHandler;
use Mrazinshaikh\LaravelMigration\Commands\{ ConfigPublishCommand, FreshCommand, InstallCommand, MakeMigrationCommand, MigrateCommand};

// Define the available commands
$commands = [
    MigrateCommand::class,
    FreshCommand::class,
    InstallCommand::class,
    MakeMigrationCommand::class,
    ConfigPublishCommand::class,
];

// Instantiate the command handler
$handler = new CommandHandler();
$handler->registerCommands($commands);

/**
 * @var array $args
 *
 * @link https://www.php.net/manual/en/reserved.variables.argv.php
 */
$args = $argv;
array_shift($args);
$command = $args[0] ?? null;
array_shift($args);

if (! $command || $command === 'list') {
    $handler->showPackageInfo();
    $handler->showAvailableCommands();
} else {
    $handler->executeCommand($command, $args);
}
